### ISSUE TITLE
Change the background-color of the website.

### ISSUE THREAD

**Issue by Saloni581** [Saloni581/Bhagwat-Mahapuran#1]
Change the Background color of the website.

**Comment by Prakhar-bansal100** [comment]
Try baby pink for background

**Comment by Saloni581** [comment]
### Okay! See this Now:
![bgcc](https://github.com/Saloni581/Bhagwat-Mahapuran/assets/125601277/f8a28e7b-326f-4a80-9b4f-7e36a3713b4f)
